spring:
  datasource:
    username: root
    password: cyber_waves_1
    # url: jdbc:mysql://10.21.14.105:3307/JDBC?characterEncoding=utf-8&&useSSL=false&&serverTimezone=UTC
    # 1、serverTimezone是配置时间区域
    # 2、url 配置规则 jdbc:mysql:// + ip地址 + 端口 / 数据库名字 ? 字符编码 && 是否使用SSL && 时间区域
    # 3、useSSL MySQL在高版本需要指明是否进行SSL连接
    url: jdbc:mysql://175.24.85.83:1006/cyber_waves?useUnicode=true&characterEncoding=utf-8&nullCatalogMeansCurrent=true&serverTimezone=Asia/Shanghai
    #    注意SpringBoot版本在2.0以前和2.0以后的配置有一些不同
    #    driver-class-name: com.mysql.jdbc.Driver SpringBoot 2.0以前的版本
    driver‐class‐name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: -1 #10MB
      max-request-size: -1 #100MB

  jackson:
    time-zone: GMT+8

  mvc:
    static-path-pattern: /static/**

server:
  port: 8088

#mybatis:
#  mapper-locations: classpath:sqlMap/UserPostDetailMapper.xml
mybatis:
  mapper-locations: classpath:mapper/*.xml
